---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: Put custom nginx.conf
    copy:
      src: ./nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted
  - name: Create empty filesystem on EBS volume
    filesystem:
      dev: /dev/nvme1n1
      fstype: ext4
  - name: Create directory for filesystem
    file:
      path: /data
      state: directory
  - name: Mount filesystem
    mount:
      src: /dev/nvme1n1
      path: /data
      fstype: ext4
      state: mounted
  - name: Generate/regenerate example data
    shell: "for i in `seq 1 100`; do dd if=/dev/urandom of=/data/example-file-${i}.bin bs=1M count=1 && chmod 777 /data/example-file-${i}.bin; done"
